# Generated by Django 6.1.2 on 2026-10-08 01:15

import django.db.models.deletion
import itens.validadores
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("perdido", "Perdido"), ("encontrado", "Encontrado")],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="título")),
                (
                    "descricao",
                    models.TextField(max_length=2000, verbose_name="descrição"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("eletronicos", "Eletrônicos"),
                            ("documentos", "Documentos"),
                            ("vestuario", "Vestuário"),
                            ("outros", "Outros"),
                        ],
                        max_length=15,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="local aproximado"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        upload_to="itens/%Y/%m/",
                        validators=[itens.validadores.validar_imagem],
                        verbose_name="foto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("perdido", "Perdido"),
                            ("encontrado", "Encontrado"),
                            ("em_verificacao", "Em verificação"),
                            ("devolvido", "Devolvido"),
                            ("arquivado", "Arquivado"),
                        ],
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="cadastrado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "itens",
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("perdido", "Perdido"),
                            ("encontrado", "Encontrado"),
                            ("em_verificacao", "Em verificação"),
                            ("devolvido", "Devolvido"),
                            ("arquivado", "Arquivado"),
                        ],
                        max_length=15,
                        verbose_name="status anterior",
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("perdido", "Perdido"),
                            ("encontrado", "Encontrado"),
                            ("em_verificacao", "Em verificação"),
                            ("devolvido", "Devolvido"),
                            ("arquivado", "Arquivado"),
                        ],
                        max_length=15,
                        verbose_name="novo status",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="observação"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="alterado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alteracoes_status",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="alterado por",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="itens.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de status",
                "verbose_name_plural": "histórico de status",
                "ordering": ["criado_em", "id"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(max_length=1000, verbose_name="comentário")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado em"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="itens.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "comentário",
                "verbose_name_plural": "comentários",
                "ordering": ["criado_em", "id"],
            },
        ),
        migrations.CreateModel(
            name="Reivindicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prova", models.CharField(max_length=500, verbose_name="comprovação")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        upload_to="reivindicacoes/%Y/%m/",
                        validators=[itens.validadores.validar_imagem],
                        verbose_name="imagem de comprovação",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("recusada", "Recusada"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "analisada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="analisada em"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviada em"),
                ),
                (
                    "analisada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reivindicacoes_analisadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="analisada por",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reivindicacoes",
                        to="itens.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reivindicacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "reivindicação",
                "verbose_name_plural": "reivindicações",
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["status"], name="itens_item_status_c22a10_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["categoria"], name="itens_item_categor_0cd1d0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reivindicacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("situacao", "pendente")),
                fields=("item", "solicitante"),
                name="uma_reivindicacao_pendente_por_usuario",
                violation_error_message="Você já tem uma reivindicação pendente para este item.",
            ),
        ),
    ]
